config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/debug'

  get 'static_pages/signup'

  get 'static_pages/signin'

  resources :rentings

  resources :travels

  resources :customers

  get 'static_pages/about'

  get 'static_pages/acquise'

  get 'static_pages/contact'

  get 'static_pages/imprint'

  get 'static_pages/login'

  get 'static_pages/help'

  
  resources :users

  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    get "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  root 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
  has_many :rentings, dependent: :destroy
  has_many :travels, dependent: :destroy
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :customer_name, presence: true, length: { maximum: 50 }
  validates :customer_street, presence: true, length: { maximum: 50 }
  validates :customer_plz, presence: true, length: { maximum: 50 }
  validates :customer_city, presence: true, length: { maximum: 50 }
  validates :customer_country, presence: true, length: { maximum: 50 }
  validates :customer_telephone, presence: true, length: { maximum: 50 }
  validates :customer_email, format: { with: VALID_EMAIL_REGEX },
                             uniqueness: { case_sensitive: false },
                             :allow_blank => true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:customer_name, :customer_street, :customer_plz, :customer_city, :customer_country, :customer_telephone, :customer_state, :customer_contact, :customer_telefax, :customer_email, :customer_homepage, :customer_is_active, :customer_show_email, :user_id)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :customer_name, required: true, autofocus: true %>
    <%= f.input :customer_contact %>
    <%= f.input :customer_street, required: true %>
    <%= f.input :customer_plz, required: true %>
    <%= f.input :customer_city, required: true %>
    <%= f.input :customer_state %>
    <%= f.input :customer_country, required: true %>
    <%= f.input :customer_telephone, as: :tel, required: true %>   
    <%= f.input :customer_telefax, as: :tel %>
    <%= f.input :customer_email, as: :email %>
    <%= f.input :customer_homepage, as: :url %>
    
    <%= f.input :customer_is_active %>
    <%= f.input :customer_show_email %>
    
    <%= f.association :user, :label_method => :email, :value_method => :id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<% provide(:dtitle, 'Only Admin') %>
<div class="container theme-showcase" role="main">
<h1>Listing customers</h1>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Customer contact</th>
      <th>Customer plz</th>
      <th>Customer city</th>
      <th>Customer telephone</th>
      <th>Customer email</th>
      <th>Customer homepage</th>
      <th>Customer is active</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.customer_name %></td>
        <td><%= customer.customer_contact %></td>
        <td><%= customer.customer_plz %></td>
        <td><%= customer.customer_city %></td>
        <td><%= customer.customer_telephone %></td>
        <td><%= customer.customer_email %></td>
        <td><%= customer.customer_homepage %></td>
        <td><%= customer.customer_is_active %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>      
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Customer', new_customer_path %>
</div>

app/views/customers/new.html.erb
<div class="container theme-showcase" role="main">
  <h1>New customer</h1>
  <%= render 'form' %>
  <%= link_to 'Back', customers_path %>
</div>

app/views/customers/show.html.erb
<div class="container theme-showcase" role="main">
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @customer.customer_name %>
</p>

<p>
  <strong>Customer street:</strong>
  <%= @customer.customer_street %>
</p>

<p>
  <strong>Customer plz:</strong>
  <%= @customer.customer_plz %>
</p>

<p>
  <strong>Customer city:</strong>
  <%= @customer.customer_city %>
</p>

<p>
  <strong>Customer country:</strong>
  <%= @customer.customer_country %>
</p>

<p>
  <strong>Customer telephone:</strong>
  <%= @customer.customer_telephone %>
</p>

<p>
  <strong>Customer state:</strong>
  <%= @customer.customer_state %>
</p>

<p>
  <strong>Customer contact:</strong>
  <%= @customer.customer_contact %>
</p>

<p>
  <strong>Customer telefax:</strong>
  <%= @customer.customer_telefax %>
</p>

<p>
  <strong>Customer email:</strong>
  <%= @customer.customer_email %>
</p>

<p>
  <strong>Customer homepage:</strong>
  <%= @customer.customer_homepage %>
</p>

<p>
  <strong>Customer is active:</strong>
  <%= @customer.customer_is_active %>
</p>

<p>
  <strong>Customer show email:</strong>
  <%= @customer.customer_show_email %>
</p>

<p>
  <strong>User:</strong>
  <%= @customer.user %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> | 
<%= link_to 'Destroy', customer_path, method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', customers_path %>
</div>