config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/debug'

  get 'static_pages/signup'

  get 'static_pages/signin'

  resources :rentings

  resources :travels

  resources :customers

  get 'static_pages/about'

  get 'static_pages/acquise'

  get 'static_pages/contact'

  get 'static_pages/imprint'

  get 'static_pages/login'

  get 'static_pages/help'

  
  resources :users

  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    get "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  root 'home#index'

end

app/models/renting.rb
class Renting < ActiveRecord::Base
  belongs_to :customer
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  before_action :set_renting, only: [:show, :edit, :update, :destroy]

  # GET /rentings
  # GET /rentings.json
  def index
    @rentings = Renting.all
  end

  # GET /rentings/1
  # GET /rentings/1.json
  def show
  end

  # GET /rentings/new
  def new
    @renting = Renting.new
  end

  # GET /rentings/1/edit
  def edit
  end

  # POST /rentings
  # POST /rentings.json
  def create
    @renting = Renting.new(renting_params)

    respond_to do |format|
      if @renting.save
        format.html { redirect_to @renting, notice: 'Renting was successfully created.' }
        format.json { render :show, status: :created, location: @renting }
      else
        format.html { render :new }
        format.json { render json: @renting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentings/1
  # PATCH/PUT /rentings/1.json
  def update
    respond_to do |format|
      if @renting.update(renting_params)
        format.html { redirect_to @renting, notice: 'Renting was successfully updated.' }
        format.json { render :show, status: :ok, location: @renting }
      else
        format.html { render :edit }
        format.json { render json: @renting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentings/1
  # DELETE /rentings/1.json
  def destroy
    @renting.destroy
    respond_to do |format|
      format.html { redirect_to rentings_url, notice: 'Renting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_renting
      @renting = Renting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def renting_params
      params.require(:renting).permit(:renting_object, :renting_min_duration, :renting_cost, :renting_cost_duration, :renting_location, :renting_region, :renting_country, :renting_display_offer, :renting_object_shortdesc, :renting_object_longdesc, :renting_gallery, :renting_header_picture, :renting_header_slider, :renting_video, :renting_calendar, :renting_form, :renting_calendar_start, :renting_calendar_end, :customer_id)
    end
end

app/helpers/rentings_helper.rb
module RentingsHelper
end

app/views/rentings/_form.html.erb
<%= simple_form_for(@renting) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :renting_object %>
    <%= f.input :renting_min_duration %>
    <%= f.input :renting_cost %>
    <%= f.input :renting_cost_duration %>
    <%= f.input :renting_location %>
    <%= f.input :renting_region %>
    <%= f.input :renting_country %>
    <%= f.input :renting_display_offer %>
    <%= f.input :renting_object_shortdesc %>
    <%= f.input :renting_object_longdesc %>
    <%= f.input :renting_gallery %>
    <%= f.input :renting_header_picture %>
    <%= f.input :renting_header_slider %>
    <%= f.input :renting_video %>
    <%= f.input :renting_calendar %>
    <%= f.input :renting_form %>
    <%= f.input :renting_calendar_start %>
    <%= f.input :renting_calendar_end %>
    <%= f.association :customer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rentings/edit.html.erb
<h1>Editing renting</h1>

<%= render 'form' %>

<%= link_to 'Show', @renting %> |
<%= link_to 'Back', rentings_path %>

app/views/rentings/index.html.erb
<h1>Listing rentings</h1>

<table>
  <thead>
    <tr>
      <th>Renting object</th>
      <th>Renting min duration</th>
      <th>Renting cost</th>
      <th>Renting cost duration</th>
      <th>Renting location</th>
      <th>Renting region</th>
      <th>Renting country</th>
      <th>Renting display offer</th>
      <th>Renting object shortdesc</th>
      <th>Renting object longdesc</th>
      <th>Renting gallery</th>
      <th>Renting header picture</th>
      <th>Renting header slider</th>
      <th>Renting video</th>
      <th>Renting calendar</th>
      <th>Renting form</th>
      <th>Renting calendar start</th>
      <th>Renting calendar end</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentings.each do |renting| %>
      <tr>
        <td><%= renting.renting_object %></td>
        <td><%= renting.renting_min_duration %></td>
        <td><%= renting.renting_cost %></td>
        <td><%= renting.renting_cost_duration %></td>
        <td><%= renting.renting_location %></td>
        <td><%= renting.renting_region %></td>
        <td><%= renting.renting_country %></td>
        <td><%= renting.renting_display_offer %></td>
        <td><%= renting.renting_object_shortdesc %></td>
        <td><%= renting.renting_object_longdesc %></td>
        <td><%= renting.renting_gallery %></td>
        <td><%= renting.renting_header_picture %></td>
        <td><%= renting.renting_header_slider %></td>
        <td><%= renting.renting_video %></td>
        <td><%= renting.renting_calendar %></td>
        <td><%= renting.renting_form %></td>
        <td><%= renting.renting_calendar_start %></td>
        <td><%= renting.renting_calendar_end %></td>
        <td><%= renting.customer %></td>
        <td><%= link_to 'Show', renting %></td>
        <td><%= link_to 'Edit', edit_renting_path(renting) %></td>
        <td><%= link_to 'Destroy', renting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Renting', new_renting_path %>

app/views/rentings/new.html.erb
<h1>New renting</h1>

<%= render 'form' %>

<%= link_to 'Back', rentings_path %>

app/views/rentings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Renting object:</strong>
  <%= @renting.renting_object %>
</p>

<p>
  <strong>Renting min duration:</strong>
  <%= @renting.renting_min_duration %>
</p>

<p>
  <strong>Renting cost:</strong>
  <%= @renting.renting_cost %>
</p>

<p>
  <strong>Renting cost duration:</strong>
  <%= @renting.renting_cost_duration %>
</p>

<p>
  <strong>Renting location:</strong>
  <%= @renting.renting_location %>
</p>

<p>
  <strong>Renting region:</strong>
  <%= @renting.renting_region %>
</p>

<p>
  <strong>Renting country:</strong>
  <%= @renting.renting_country %>
</p>

<p>
  <strong>Renting display offer:</strong>
  <%= @renting.renting_display_offer %>
</p>

<p>
  <strong>Renting object shortdesc:</strong>
  <%= @renting.renting_object_shortdesc %>
</p>

<p>
  <strong>Renting object longdesc:</strong>
  <%= @renting.renting_object_longdesc %>
</p>

<p>
  <strong>Renting gallery:</strong>
  <%= @renting.renting_gallery %>
</p>

<p>
  <strong>Renting header picture:</strong>
  <%= @renting.renting_header_picture %>
</p>

<p>
  <strong>Renting header slider:</strong>
  <%= @renting.renting_header_slider %>
</p>

<p>
  <strong>Renting video:</strong>
  <%= @renting.renting_video %>
</p>

<p>
  <strong>Renting calendar:</strong>
  <%= @renting.renting_calendar %>
</p>

<p>
  <strong>Renting form:</strong>
  <%= @renting.renting_form %>
</p>

<p>
  <strong>Renting calendar start:</strong>
  <%= @renting.renting_calendar_start %>
</p>

<p>
  <strong>Renting calendar end:</strong>
  <%= @renting.renting_calendar_end %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @renting.customer %>
</p>

<%= link_to 'Edit', edit_renting_path(@renting) %> |
<%= link_to 'Back', rentings_path %>