config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/debug'

  get 'static_pages/signup'

  get 'static_pages/signin'

  resources :rentings

  resources :travels

  resources :customers

  get 'static_pages/about'

  get 'static_pages/acquise'

  get 'static_pages/contact'

  get 'static_pages/imprint'

  get 'static_pages/login'

  get 'static_pages/help'

  
  resources :users

  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    get "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  root 'home#index'

end

app/views/layouts/_debug.html.erb
<div id="debug" class="container">
  <%= debug(params) if Rails.env.development? %>
</div>

app/views/layouts/_error.html.erb
<div id="error" class="container">
	<% if Rails.env.development? %>	  
	    <%= debug_info(yield(:dtitle)) %>
	<% end %>
	<% [:notice, :error, :alert, :success].each do |level| %>
	  <% unless flash[level].blank? %>
	    <div class="<%= flash_class(level) %>">
	      <%= content_tag :span, flash[level] %>
	    </div>
	  <% end %>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
<% if Rails.env.development? %>

<% else %>
<div id="footer">
  <div class="container">
    <p class="text-muted">Place sticky footer content here.</p>
  </div>
</div>
<% end %>

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Bootstrap theme</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Static Pages <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "About", static_pages_about_path %></li>
            <li><%= link_to "Acquise", static_pages_acquise_path %></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
            <li><%= link_to "Help", static_pages_help_path %></li>
            <li><%= link_to "Imprint", static_pages_imprint_path %></li>
            <li><%= link_to "SignIn", static_pages_signin_path %></li>
            <li><%= link_to "SignUp", static_pages_signup_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Customers <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Index", customers_path %></li>
            <li><%= link_to "New", new_customer_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Rentings <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Index", rentings_path %></li>
            <li><%= link_to "New", new_renting_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Travels <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Index", travels_path %></li>
            <li><%= link_to "New", new_travel_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Index", users_path %></li>
            <li><%= link_to "New", new_user_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "LogIn", new_user_session_path %></li>
            <li><%= link_to "LogOut", destroy_user_session_path %></li>
            <li><%= link_to "Debug", static_pages_debug_path %></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_meta.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Info3 Reiseportal">
<meta name="author" content="Simon Knipping">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I3travels</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/meta' %>	
</head>
<body role="document"> 
  <%= render 'layouts/header' %>
  <%= render 'layouts/error' %>
  
  <%= yield %>
  
  <%= render 'layouts/debug' %>
  <%= render 'layouts/footer' %>
</body>
</html>